spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/Koko?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: '0204'

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 239665432573-732lr7l752fu06lik16pd1mfhts3ep74.apps.googleusercontent.com
            client-secret: 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
            scope:
              - profile
              - email

          kakao:
            client-id: e4042c92475ffbcb48fd471fc476f65e
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            client-authentication-method: POST
            client-name: Kakao
            scope:
              - profile_nickname
              - account_email

        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace


ffmpeg:
  #mpeg: /opt/homebrew/bin/ffmpeg
  #probe: /opt/homebrew/bin/ffprobe
  #savePath: /Users/jeon-sangeon/Desktop/koko_store/

  mpeg: C:\ffmpeg\bin\ffmpeg
  probe: C:\ffmpeg\bin\ffprobe
  savePath: C:\Users\User\Desktop\audio\

  #mpeg: C:\Users\tkd02\Downloads\ffmpeg-6.0-essentials_build\ffmpeg-6.0-essentials_build\bin\ffmpeg.exe
  #probe: C:\Users\tkd02\Downloads\ffmpeg-6.0-essentials_build\ffmpeg-6.0-essentials_build\bin\ffprobe.exe
  #savePath: C:\Users\User\Desktop\audio\

file:
  dir: C:\Users\User\Desktop\koko_store\
  feedbackDir: C:\Users\User\Desktop\koko_store\feedback_audio\
  spectroDir : C:\Users\User\Desktop\koko_store\spectro\
  #dir: /Users/jeon-sangeon/Desktop/koko_store/feedback_audio
  #dir: C:\Users\tkd02\OneDrive\바탕 화면\koko_store\
  #feedbackDir: C:\Users\tkd02\OneDrive\바탕 화면\koko_store\feedback_audio\



